name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Build
        run: dotnet publish -c Release -r win-x64 --self-contained true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: bin/Release/net6.0/win-x64/publish/
